---

- name: Debug OS Version
  debug:
    msg: "distribution: {{ ansible_distribution }}, major_version: {{ ansible_distribution_major_version }}"

- name: Add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/defaults.yml"

- include: radvd_daemon.yml
  when: (radvd_daemon_run|bool)

- name: RADVD dead man's switch 
  debug:
    msg: "Skipped RADVD configuration because dead man's switch var 'radvd_daemon_run' is not set to true"
  when: not radvd_daemon_run|bool